New log file opened at Wed Nov 30 18:27:55 EST 2016 by 4460@T-Dell
Taking next connection to: 61029
New client attempting to connect on port: 61030-61029
  Address = /172.20.84.202:61029
This client on port 61030 has uuid ea1f301b-eac5-4d0f-8e87-51e5f99de5e0 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-ea1f301b-eac5-4d0f-8e87-51e5f99de5e0
Taking next connection to: 61029
New client attempting to connect on port: 61031-61029
  Address = /172.20.84.202:61029
Handshake exception on socket: 61031
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 61029
New client attempting to connect on port: 61032-61029
  Address = /172.20.84.202:61029
This client on port 61032 has uuid 8705b45e-25d8-48af-ba30-5b896463c2b8 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-ea1f301b-eac5-4d0f-8e87-51e5f99de5e0, activator-8705b45e-25d8-48af-ba30-5b896463c2b8
Taking next connection to: 61029
New client attempting to connect on port: 61034-61029
  Address = /172.20.84.202:61029
Handshake exception on socket: 61034
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 61029
New client attempting to connect on port: 61035-61029
  Address = /172.20.84.202:61029
This client on port 61035 has uuid 9b87c8dd-96e9-49d8-87d5-b43df413d257 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-8705b45e-25d8-48af-ba30-5b896463c2b8, play-fork-run-9b87c8dd-96e9-49d8-87d5-b43df413d257
Taking next connection to: 61029
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 61029
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 61029
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 61029
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 61029
